# Ejercicio 2

###  Python: API APOD de la NASA

**Preguntas del equipo:**
* ¿Qué tipo de parámetros admite la solicitud?
* ¿Qué tipo respuestas se pueden obtener con cada solicitud?
* ¿Qué tipo de restricciones tiene la API?

**Preguntas de cada miembro del equipo:**

1. Para las búsquedas de tu palabra, ¿cuántos resultados obtuviste?
2. Para las búsquedas de tu palabra, ¿en qué rangos de fechas se introdujo el recurso?
3. Para las búsquedas de tu palabra, ¿cuáles son los "media_type" más comunes?
4. Para las búsquedas de tu palabra, ¿quiénes son los autores o instituciones propietaria de los derechos (i.e. el copyright)?

1. ¿Qué tipo de parámetros admite la solicitud?

Las consultas a la API admiten los siguintes parametros:

* **api_key**: la llave para acceder a la API, puede ser una llave publica (imita la cantidad de consultas) o una llave personal generada de forma gratuita en el sitio
* **date**: Una cadena de texto en formato AAAA-MM-DD que indica la fecha de la imagen APOD a consultar (ejemplo: 2002-12-03). En caso de no intrudicir una fecha se utiliza la fecha actual al momento de la consulta.
* **start_date**: Una cadena de texto en formato AAAA-MM-DD que indica el inicio de un rango de fechas, se usa en conjuntoa end_dete para crear un intervalo de tiempo.
* **end_date**: Una cadena de texto en formato AAAA-MM-DD que indica el fin de un rango de fechas, se usa en conjuntoa start_dete para crear un intervalo de tiempo.
* **concept_tags**: Un valor booleano True o False que indica si las etiquetas de concept deben devolverse junto con el resto de la respuesta.
* **hd** : Un valor booleano True o False que indica si se deben devolver imágenes de alta resolución.
* **count** : Un número entero positivo, que si se especifica, se devolverán imágenes elegidas aleatoriamente en una matriz JSON.
* **thumbs**: Un valor booleano True o False que indica si la API debe devolver la URL de la imagen en miniatura para los archivos de vídeo.

Pese a que la API APOD tiene todos estos parámetros para las consultas, no todos se pueden usar al mimso timepo y existenen ciertas restricciones para las consultas, dichas restricciones se comentaran mas adelante.

2. ¿Qué tipo respuestas se pueden obtener con cada solicitud?

La API, generalmente devolvera un diccionario o una lista de diccionaros, segun sea el tipo de solicitud.

Si en nuestra solicitud usamos el parametro date, es decir consultamos un unico día la api devuelve un diccionario JSON, cuando en nuestra consulta usamos los parametros start_date y end_date o el parametro count, la API nos devolverá una lista de diccionaros.

Tambien podemos tener respuestas de error

3. ¿Qué tipo de restricciones tiene la API?

La API APOD cuenta con 2 tipos de restricciones

1. **Restricció en cantidad de consultas**

Usando una API KEY de prueba se tienen límites por IP muy bajos:

* 30 consultas por hora
* 50 consultas por día

Usando una API KEY propia

* Se obtiene un limite de  1000 requests por hora

2. **Restriccion en estructura de consulta**

La principal restriccion al momento de hacer nuestras consultas son con las fechas

* **Primer fecha**: APOD solo tiene registros desde: 1995-06-16, por lo que la consulta debe hacerce posterior a esta fecha y no mayor a la fecha actual.
* **Convinación de parametros**: No es posible usar los siguintes parametos juntos : date, start_date, end_date o count, la  unica conbinación posible es start_date y end_date para consultar intervalos de fechas

**Palabras correspondientes al número de la primera letra del apellido paterno de cada integrante del equipo:**

*   Aguilera Yáñez Mariana --> ***gravitational***
*   Alvarado Arce Axel Eduardo --> ***retrograde***
*   Canseco Galván Tanivet --> ***supernova***
*   Garcia Soto Kevin --> ***nebula***
*   Hernandez Mareles Francisco Javier --> ***planetary***
*   Rendon Cardoso Karla --> ***Geminids***
*   Suarez Urbano David Hiram --> ***Einstein***

Pimero contruiremos el codigo para acceder a los datos medinate la API APOD de la NASA

In [ ]:
import requests
import pandas as pd
import time
from datetime import datetime, timedelta

In [ ]:
def get_apod_dataframe(api_key, start_date, end_date):
    url = "https://api.nasa.gov/planetary/apod"

    start = datetime.strptime(start_date, "%Y-%m-%d")
    end = datetime.strptime(end_date, "%Y-%m-%d")

    # Para evitar errores de la API usaremos maximo bloques de 100 dias
    a = timedelta(days=100)
    inicio = start

    all_data = []

    while inicio <= end:
        chunk_end = min(inicio + a, end)

        params = {
            "api_key": api_key,
            "start_date": inicio.strftime("%Y-%m-%d"),
            "end_date": chunk_end.strftime("%Y-%m-%d"),
            "thumbs": True  # para obtener thumbnail en videos
        }

        response = requests.get(url, params=params)

        if response.status_code == 200:
            data = response.json()

            # para evitar errores de lista
            if isinstance(data, dict):
                data = [data]

            for item in data:
                all_data.append({
                    "resource": item.get("resource"),
                    "concept_tags": item.get("concept_tags"),
                    "title": item.get("title"),
                    "date": item.get("date"),
                    "url": item.get("url"),
                    "hdurl": item.get("hdurl"),
                    "media_type": item.get("media_type"),
                    "explanation": item.get("explanation"),
                    "concepts": item.get("concepts"),
                    "thumbnail_url": item.get("thumbnail_url"),
                    "copyright": item.get("copyright"),
                    "service_version": item.get("service_version")
                })

        else:
            print(f"Error {response.status_code} en rango {inicio} - {chunk_end}")

        # pausa para evitar que la api nos bloque
        time.sleep(1)

        inicio = chunk_end + timedelta(days=1)

    # Convertir a DataFrame
    df = pd.DataFrame(all_data)

    return df

In [ ]:
df = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2003-04-13",
    end_date="2003-05-13"
)

df

,resource,concept_tags,title,date,url,hdurl,media_type,explanation,concepts,thumbnail_url,copyright,service_version
0,None,None,NGC 1365: A Nearby Barred Spiral Galaxy,2003-04-13,https://apod.nasa.gov/apod/image/0304/ngc1365_...,https://apod.nasa.gov/apod/image/0304/ngc1365_...,image,Many spiral galaxies have bars across their ce...,None,None,None,v1
1,None,None,A Gamma Ray Burst - Supernova Connection,2003-04-14,https://apod.nasa.gov/apod/image/0304/ngc3184_...,https://apod.nasa.gov/apod/image/0304/ngc3184_...,image,New evidence has emerged that a mysterious typ...,None,None,None,v1
2,None,None,A Crescent Nebula Star Field,2003-04-15,https://apod.nasa.gov/apod/image/0304/crescent...,https://apod.nasa.gov/apod/image/0304/crescent...,image,What caused the Crescent Nebula? Looking like...,None,None,T. A. Rector,v1
3,None,None,Magma Bubbles from Mt. Etna,2003-04-16,https://apod.nasa.gov/apod/image/0304/etnabubb...,https://apod.nasa.gov/apod/image/0304/etnabubb...,image,Mt. Etna erupted spectacularly in 2001 June. ...,None,None,Stromboli online,v1
4,None,None,M106 in Canes Venatici,2003-04-17,https://apod.nasa.gov/apod/image/0304/m106_blo...,https://apod.nasa.gov/apod/image/0304/m106_blo...,image,Close to the Great Bear (Ursa Major) and surro...,None,None,None,v1
5,None,None,Double Eruptive Prominences,2003-04-18,https://apod.nasa.gov/apod/image/0304/doublepr...,https://apod.nasa.gov/apod/image/0304/doublepr...,image,Lofted over the Sun on looping magnetic fields...,None,None,None,v1
6,None,None,Spiral Galaxy In Centaurus,2003-04-19,https://apod.nasa.gov/apod/image/0304/eso269_v...,https://apod.nasa.gov/apod/image/0304/eso269_v...,image,"Centaurus, the Centaur, is one of the most str...",None,None,None,v1
7,None,None,The Gum Nebula Supernova Remnant,2003-04-20,https://apod.nasa.gov/apod/image/0304/gum_glea...,https://apod.nasa.gov/apod/image/0304/gum_glea...,image,Because the Gum Nebula is the closest supernov...,None,None,John Gleason (Celestial Images),v1
8,None,None,A Halo Around the Moon,2003-04-21,https://apod.nasa.gov/apod/image/0304/moonhalo...,https://apod.nasa.gov/apod/image/0304/moonhalo...,image,Tomorrow's picture: North Mars < | Archive | ...,None,None,Sarah McKay,v1
9,None,None,Springtime on Mars,2003-04-22,https://apod.nasa.gov/apod/image/0304/marsnort...,https://apod.nasa.gov/apod/image/0304/marsnort...,image,"Vast canyons, towering volcanoes, sprawling fi...",None,None,None,v1
10,None,None,The Stars of NGC 1705,2003-04-23,https://apod.nasa.gov/apod/image/0304/ngc1705_...,https://apod.nasa.gov/apod/image/0304/ngc1705_...,image,"Some 2,000 light-years across, NGC 1705 is sma...",None,None,None,v1
11,None,None,Earth at Twilight,2003-04-24,https://apod.nasa.gov/apod/image/0304/earthter...,https://apod.nasa.gov/apod/image/0304/earthter...,image,"No sudden, sharp boundary marks the passage of...",None,None,None,v1
12,None,None,M17: A Hubble Close-Up,2003-04-25,https://apod.nasa.gov/apod/image/0304/m17close...,https://apod.nasa.gov/apod/image/0304/m17close...,image,"Sculpted by stellar winds and radiation, these...",None,None,None,v1
13,None,None,Big Blue Marble Earth,2003-04-26,https://apod.nasa.gov/apod/image/0304/bluemarb...,https://apod.nasa.gov/apod/image/0304/bluemarb...,image,This reconstructed digital portrait of our pla...,None,None,None,v1
14,None,None,Venus' Once Molten Surface,2003-04-27,https://apod.nasa.gov/apod/image/0003/venus4_m...,https://apod.nasa.gov/apod/image/0003/venus4_m...,image,If you could look at Venus with radar eyes - t...,None,None,None,v1
15,None,None,Rollout of a Soyuz TMA-2 Aboard an R7 Rocket,2003-04-28,https://apod.nasa.gov/apod/image/0304/tma2_nas...,https://apod.nasa.gov/apod/image/0304/tma2_nas...,image,It takes a big rocket to go into space. Last ...,None,None,None,v1
16,None,None,In the Center of the Rosette Nebula,2003-04-29,https://apod.nasa.gov/apod/image/0304/rosette_...,https://apod.nasa.gov/apod/image/0304/rosette_...,image,In the heart of the Rosette Nebula lies a brig...,None,None,"MegaPrime Camera,\nCanada-France-Hawaii Telescope",v1
17,None,None,A Lenticular Cloud Over New Hampshire,2003-04-30,https://apod.nasa.gov/apod/image/0304/lenticul...,https://apod.nasa.gov/apod/image/0304/lenticul...,image,Why does this cloud look so strange? Actually...,None,None,"J. D. Rufo, \nJ. Koermer, \nPlymouth State Col...",v1
18,None,None,The Energetic Jet from Centaurus A,2003-05-01,https://apod.nasa.gov/apod/image/0305/cenajet_...,https://apod.nasa.gov/apod/image/0305/cenajet_...,image,The center of well-studied active galaxy Centa...,None,None,None,v1
19,None,None,Five to Mars,2003-05-02,https://apod.nasa.gov/apod/image/0305/marsglob...,https://apod.nasa.gov/apod/image/0305/marsglob...,image,"Come December 2003 - January 2004, an armada o...",None,None,None,v1
20,None,None,Denizen of the Tarantula Nebula,2003-05-03,https://apod.nasa.gov/apod/image/0305/hodge301...,https://apod.nasa.gov/apod/image/0305/hodge301...,image,"The star cluster at lower right, cataloged as ...",None,None,None,v1
21,None,None,A Sonic Boom,2003-05-04,https://apod.nasa.gov/apod/image/0102/sonicboo...,https://apod.nasa.gov/apod/image/0102/sonicboo...,image,"Many people have heard a sonic boom, but few h...",None,None,None,v1
22,None,None,NGC 1275: A Galactic Collision,2003-05-05,https://apod.nasa.gov/apod/image/0305/ngc1275_...,https://apod.nasa.gov/apod/image/0305/ngc1275_...,image,"In NGC 1275, one galaxy is slicing through ano...",None,None,None,v1
23,None,None,A Chicago Meteorite Fall,2003-05-06,https://apod.nasa.gov/apod/image/0305/chicagof...,https://apod.nasa.gov/apod/image/0305/chicagof...,image,"If you wait long enough, a piece of outer spac...",None,None,Ivan and Colby Navarro,v1
24,None,None,The Southern Sky from the International Space ...,2003-05-07,https://apod.nasa.gov/apod/image/0305/southern...,https://apod.nasa.gov/apod/image/0305/southern...,image,"Look up from Earth's South Pole, and this stel...",None,None,None,v1
25,None,None,Mercury Spotting,2003-05-08,https://apod.nasa.gov/apod/image/0305/merctran...,https://apod.nasa.gov/apod/image/0305/merctran...,image,Can you spot the planet? The diminutive disk o...,None,None,None,v1
26,None,None,International Space Station in Transit,2003-05-09,https://apod.nasa.gov/apod/image/0305/isstrans...,https://apod.nasa.gov/apod/image/0305/isstrans...,image,A stunning telescopic image of the Internation...,None,None,Tom Laskowski,v1
27,None,None,NGC 7293: The Helix Nebula,2003-05-10,https://apod.nasa.gov/apod/image/0305/helix03_...,https://apod.nasa.gov/apod/image/0305/helix03_...,image,Will our Sun look like this one day? The Heli...,None,None,None,v1
28,None,None,M83: The Southern Pinwheel Galaxy from VLT,2003-05-11,https://apod.nasa.gov/apod/image/0305/m83_vlt.jpg,https://apod.nasa.gov/apod/image/0305/m83_vlt_...,image,M83 is one of the closest and brightest spiral...,None,None,None,v1
29,None,None,In the Vicinity of the Cone Nebula,2003-05-12,https://apod.nasa.gov/apod/image/0305/coneregi...,https://apod.nasa.gov/apod/image/0305/coneregi...,image,Strange shapes and textures can be found in ne...,None,None,T. A. Rector,v1
30,None,None,Mercury Transits the Sun,2003-05-13,https://apod.nasa.gov/apod/image/0305/mercurys...,https://apod.nasa.gov/apod/image/0305/mercurys...,image,How big is the Sun? The Sun is not only large...,None,None,Thierry Legault,v1

In [ ]:
import pandas as pd

def analizar_apod(df, palabra_clave):
    # Solo para asegurar que sienpre sea un str
    df["explanation"] = df["explanation"].astype(str)

    # Filtramos por palabra
    df_filtrado = df[df["explanation"].str.contains(palabra_clave, case=False, na=False)]

    # Numero de resultados
    total_resultados = len(df_filtrado)

    # Media_type
    media_types = df_filtrado["media_type"].value_counts()

    # Copyrights
    copyrights = (
        df_filtrado["copyright"]
        .dropna()
        .value_counts()
    )

    return {
        "total": total_resultados,
        "media_types": media_types,
        "copyrights": copyrights,
        "df_filtrado": df_filtrado
    }

In [ ]:
resultado = analizar_apod(df, "Nebula")

*   Aguilera Yáñez Mariana --> ***gravitational***

In [ ]:
df_Mariana = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2010-08-20",
    end_date="2010-11-20"
)

resultado1 = analizar_apod(df_Mariana, "gravitational")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": [ "Aguilera Yañez Mariana",
               "2010-08-20 al 2010-11-20",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

*   Alvarado Arce Axel Eduardo --> ***retrograde***

In [ ]:
df_Eduardo = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2006-03-10",
    end_date="2010-07-19"
)

resultado1 = analizar_apod(df_Eduardo, "retrograde")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": [ "Alvarado Arce Axel Eduardo",
               "2006-03-10 al 2010-07-19",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

*   Canseco Galván Tanivet --> ***supernova***

In [ ]:
df_Tanivet = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2012-09-21",
    end_date="2013-05-7"
)

resultado1 = analizar_apod(df_Tanivet, "supernova")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": [ "Canseco Galván Tanivet",
               "2012-09-21 al 2013-05-7",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

*   Garcia Soto Kevin --> ***nebula***

In [ ]:
df_Kevin = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2010-06-28",
    end_date="2013-09-03"
)

resultado1 = analizar_apod(df_Kevin, "nebula")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": [ "Garcia Soto Kevin",
               "2010-06-28 al 2013-09-03",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

*   Hernandez Mareles Francisco Javier --> ***planetary***

In [ ]:
df_Javier = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2017-01-15",
    end_date="2018-08-29"
)

resultado1 = analizar_apod(df_Javier, "planetary")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": [ "Hernandez Mareles Francisco Javier",
               "2017-01-15 al 2018-08-29",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

*   Rendon Cardoso Karla --> ***Geminids***

In [ ]:
df_Karla = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2023-07-26",
    end_date="2026-04-02"
)

resultado1 = analizar_apod(df_Karla, "Geminids")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": [ "Rendon Cardoso Karla",
               "2023-07-26 al 2026-04-02",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

*   Suarez Urbano David Hiram --> ***Einstein***

In [ ]:
df_David = get_apod_dataframe(
    api_key="S1ba65tHYH5KWWPUVwYfnGs3wpdXYf6TDMBQSQqk",
    start_date="2009-09-08",
    end_date="2012-07-12"
)

resultado1 = analizar_apod(df_David, "Einstein")

In [ ]:
import pandas as pd

# Convertir copyrights a lista de texto
lista_copyrights = ", ".join(
    [f" {nombre}: {cantidad}"
     for nombre, cantidad in resultado1['copyrights'].items()]
)


# Diccionario con los datos
datos_resumen = {
    "Concepto": ["Alumno","Intervalo de fechas", "Palabra buscada",
                 "Total de Resultados", "Media Type Imagen", "Media Type Videos",
                  "Copyrights"],
    "Valor": ["Suarez Urbano David Hiram",
               "2009-09-08 al 2012-07-12",
               "gravitational",
               resultado1['total'],
               resultado1['media_types'].get('image', 0),
               resultado1['media_types'].get('video', 0),
               lista_copyrights
    ]
}

# Convertimos a DataFrame
df_final = pd.DataFrame(datos_resumen)
display(df_final.style.hide(axis="index"))

**CONCLUSIONES GENERALES:**

El análisis que se hizo en la API APOD de la NASA muestra contenido astronómico y multimedia.
Los resultados obtenidos dependen de la palabra clave y el parametro del rango de fechas, aparecieron imagenes, videos, diferentes autores. Demostrando que la API es una colección dinamica de contenido cientifico y también divulgativo.

Palabras como *nebula*, *supernova*, *planetary*, tuvieron más resultados porque son conceptos comunes en astronomía, generando mucho contenido visual, es por eso que se generaron más resultados de media y múltiples autores.
Mientras palabras como *retrograde*, *einstein*, *gravitational*, generarón menos resultados ya que son conceptos más específicos .

El tipo de resultados en el tipo de media, en algunos casos se obtuvieron imágenes en otroa videos o ambos, esto depende del fenómenos astronómico ya que muchos de ellos se explican mejor mediante animaciones.
El campo de copyrights evidencia que la APOD utiliza contenido de astrónomos, fotógrafos, observatorios, agencias, funcionando también como una plataforma de difusión cientifica colaboratuiva.